---
title: "Jour2 2022"
output: html_document
date: "2025-04-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

Part 1

```{r}
read_lines("input22022.txt") |>
  as.tibble() -> strategy
strategy
```

```{r}
strategy |>
  separate(col = value, into = c("col1", "col2"), sep = " ") -> strategy1
strategy1
```

```{r}
strategy1 |>
  mutate(score1 = case_when(
    col1 == "A" ~ "1",  
    col1 == "B" ~ "2",  
    col1 == "C" ~ "3")) |>
  mutate(score2 = case_when(
    col2 == "X" ~ "1",  
    col2 == "Y" ~ "2",  
    col2 == "Z" ~ "3")) -> strategy2
strategy2
```

```{r}
strategy2 |>
  mutate(object1 = case_when(
    col1 == "A" ~ "rock",  
    col1 == "B" ~ "paper",  
    col1 == "C" ~ "scissors")) |>
  mutate(object2 = case_when(
    col2 == "X" ~ "rock",  
    col2 == "Y" ~ "paper",  
    col2 == "Z" ~ "scissors")) -> strategy3
strategy3
```



```{r}
strategy3 |>
  mutate(
    score1 = as.numeric(score1),
    score2 = as.numeric(score2)) |>
    mutate(points1 = case_when(
      object1 == "scissors" & object2 == "rock" ~ 6,
      object1 == "scissors" & object2 == "paper" ~ 0,
      object1 == "paper" & object2 == "rock" ~ 0,
      object1 == "paper" & object2 == "scissors" ~ 6,
      object1 == "rock" & object2 == "paper" ~ 6,
      object1 == "rock" & object2 == "scissors" ~ 0,
      object1 == "rock" & object2 == "rock" ~ 3,
      object1 == "scissors" & object2 == "scissors" ~ 3,
      object1 == "paper" & object2 == "paper" ~ 3)) -> strategy6
strategy6
```


```{r}
strategy6 |>
  mutate(total = points1 + score2) -> strategy7
strategy7
```

```{r}
strategy7 |>
  summarise(totsum = sum(total))
```


9737 * too low
10308

PART 2
```{r}
strategy1
```

```{r}
strategy2 |>
  mutate(object1 = case_when(
    col1 == "A" ~ "rock",  
    col1 == "B" ~ "paper",  
    col1 == "C" ~ "scissors")) |>
  mutate(object2 = case_when(
    col2 == "X" ~ "lose",  
    col2 == "Y" ~ "raw",  
    col2 == "Z" ~ "win")) -> strateg1
strateg1
```

```{r}
strateg1 |>
  mutate(score = case_when(
    object2 == "raw" ~ "3",  
    object2 == "win" ~ "6",  
    object2 == "lose" ~ "0")) -> strateg2
strateg2
```

```{r}
strateg2 |>
  mutate(object3 = case_when(
    score == "3" ~ object1,
    score == "0" ~ ifelse(object1 == "paper", "rock",
                          ifelse(object1 == "scissors", "paper",
                                 ifelse(object1 == "rock", "scissors", NA))),
    score == "6" ~ ifelse(object1 == "paper", "scissors",
                          ifelse(object1 == "scissors", "rock",
                                 ifelse(object1 == "rock", "paper", NA))))) ->strateg3
strateg3
```


```{r}
strateg3 |>
  mutate(total1 = case_when(
    object3 == "paper" ~ "2",  
    object3 == "rock" ~ "1",  
    object3 == "scissors" ~ "3")) -> strateg4
strateg4
```

```{r}
strateg4 |>
  mutate(
    score = as.numeric(score),
    total1 = as.numeric(total1)) |>
  mutate(totalf = total1 + score) |>
  summarise(sum(totalf))
```

