---
title: "Jour 4 2022"
output: html_document
date: "2025-04-25"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

Part 1


```{r}
read_lines("input42022.txt") |>
  as_tibble() -> pairs
pairs
```

```{r}
pairs |>
  rowwise() |>
   mutate(
    col1 = str_split_1(value, ",")[1],
    col2 = str_split_1(value, ",")[2]) -> cols
cols
```

```{r}
cols |>
  mutate(
    col1 = str_replace_all(col1, "-", ":"),
    col2 = str_replace_all(col2, "-", ":")) -> cols1
cols1
```

```{r}
cols1 |>
  mutate(col1_range = map(col1, ~ eval(parse(text = .x)))) |>
  mutate(col2_range = map(col2, ~ eval(parse(text = .x)))) -> cols2
cols2
```

```{r}
cols2 |>
  select(col1_range, col2_range) |> 
  rowwise() |>
  rowwise() %>%
  mutate(is_subset = all(col1_range %in% col2_range)) |>
  filter(is_subset) |>
  nrow()
```


```{r}
cols2 |>
  select(col1_range, col2_range) |> 
  rowwise() |>
  mutate(is_subset = all(col1_range %in% col2_range) | all(col2_range %in% col1_range)) |>
  filter(is_subset) |>
  nrow()
```

256 too low

Part 2

```{r}
cols2 |>
  select(col1_range, col2_range) |> 
  rowwise() |>
  mutate(is_subset = any(col1_range %in% col2_range))|>
  filter(is_subset) |>
  nrow()
```



